/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NextDays: typeof import('./components/NextDays.vue')['default']
    NextHours: typeof import('./components/NextHours.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
